---

- hosts: project_1
  sudo: yes
  tasks:


  - name: update repository index
    apt:
      update_cache: yes
    when: ansible_distribution in ["Debian",  "Ubuntu"]

  - name: install apache2 package
    apt:
      name: apache2
      state: latest
    when: ansible_distribution in ["Debian", "Ubuntu"]

  - name: install php support for apache
    apt:
      name: php5
      state: latest
